### ISSUE TITLE
Apparent double nesting of rubies impacting ruby spacing and baseline shifts (when rubyReserve is used)

### ISSUE THREAD

**Issue by jbaden** [sandflow/imscJS#184] opened 2020-06-04 23:23 UTC
Hello, 

There appears to be a bug in IMSC.js resulting in double/nested rubies when rubyReserve is used.  This issue is illustrated in the attached test file [rubyReserve005_NFLX_Sample.xml.zip](https://github.com/sandflow/imscJS/files/4733088/rubyReserve005_NFLX_Sample.xml.zip)

In order to render correctly, ruby events appear to require non-space characters at the beginning of a line _**both before and outside of the ruby container**_. That is to say, a ruby event cannot begin with tts:ruby="container" else this double/nested ruby rendering issue will occur. 

_**without non-space character**_

```
            <p begin="850000000t" dur="10000000t" region="bottom-left-justified">
                <span style="ruby-outside-container"><span style="ruby-base">太孫</span><span style="ruby-text">たいそん</span></span>のペクチョンを連れ<br/>
                <span style="ruby-outside-container"><span style="ruby-base">北漢</span><span style="ruby-text">プッカン</span></span>山に登り</p>       
```
[
![without_non_space_Character](https://user-images.githubusercontent.com/25715295/83818961-773f9580-a67d-11ea-831e-389dd51912f9.png)
](url)

_**with non-space character**_

```
            <p begin="870000000t" dur="10000000t" region="bottom-left-justified">
                太<span style="ruby-outside-container"><span style="ruby-base">太孫</span><span style="ruby-text">たいそん</span></span>のペクチョンを連れ<br/>
                太<span style="ruby-outside-container"><span style="ruby-base">北漢</span><span style="ruby-text">プッカン</span></span>山に登り</p> 
```
![with_non_space_character](https://user-images.githubusercontent.com/25715295/83818983-89b9cf00-a67d-11ea-86ae-180972c8fd38.png)

**Comment by palemieux** [comment] 2020-06-05 05:42
To polyfill `tts:rubyReserve`, `applyRubyReserve()` inserts a zero-width ruby annotation before the first HTML span in each line. This breaks if the first span is itself within a ruby annotation. Probably can be fixed. 

https://github.com/sandflow/imscJS/blob/060e583c3ff1ecbf8743d6a9ff57b1d3fc253b65/src/main/js/html.js#L782

**Comment by jbaden** [comment] 2020-06-16 21:26
Thank you, @palemieux! 

Would you happen to have a target date for the [1.1.2 release](https://github.com/sandflow/imscJS/milestone/10)?

Much Appreciated, 
Justin

**Comment by palemieux** [comment] 2020-06-17 15:11
> Would you happen to have a target date for the 1.1.2 release?

@jbaden It would be good to catch all blocking issues in that release. Anything else from you?

**Comment by palemieux** [comment] 2020-06-18 00:24
@jbaden See #187. I have deployed it at http://sandflow.com/imsc1_1/index.html (be sure to hit Shift-F5). Looking forward to your feedback.

**Comment by jbaden** [comment] 2020-06-18 16:45
Thank you, @palemieux. It looks like this issue has now been resolved. That said, I did want to call your attention to what I believe to be a browser-related issue. There appears to be relative movement of the baseline text in the 1-line event "with" and "without" rubies. See events timed at (88 & 89).  I noticed that this very slight shift only occurs in Firefox, but not in Chrome, which makes me think this is more of a browser issue and not an issue with imscJS.  Thanks!

**Comment by palemieux** [comment] 2020-06-18 20:11
@jbaden Thanks for the review. The issue at https://github.com/sandflow/imscJS/issues/184#issuecomment-646160340 was in fact caused by style properties not being copied correctly to the hidden `ruby` element emulating `rubyReserve`, i.e. Firefox was correct and Chrome incorrect. It is fixed now.

**Closed** 2020-06-23 20:05 UTC
Labels: 1.1, bug

**Comment by jbaden** [comment] 2020-06-23 21:53
Hi @palemieux, 

After further testing and review, I believe the rubyReserve issue you identified may also impact boutens (tts:textEmphasis).

_"To polyfill tts:rubyReserve, applyRubyReserve() inserts a zero-width ruby annotation before the first HTML span in each line. This breaks if the first span is itself within a ruby annotation. Probably can be fixed."_

In the following XML excerpts & corresponding images generated from IMSC11 Renderer, I've noticed that the baseline shifts when boutens are applied if they are exercised at the very beginning of a line (Example 2). In Example 3, I've added punctuation before the tts:textEmphasis span and the baseline is preserved (as expected with rubyReserve): 

**Example 1**

**_2-line Horizontal Event without Boutens; with rubyReserve:_** 
`<p begin="100000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start">強調したい時に使<br/>強調したい時に使</p>`

![noBoutens](https://user-images.githubusercontent.com/25715295/85465672-ea8e4600-b55d-11ea-8a54-5bb01433898c.png)

**Example 2**

**_2-line Horizontal Event with Boutens + rubyReserve (no preceding character/punctuation before span tts:textEmphasis)_** 
`<p begin="120000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start"><span style="bouten-filled-circle-outside">強調したい時に使<br/>強調したい時に使</span></p>`

![withBoutens](https://user-images.githubusercontent.com/25715295/85466352-b5cebe80-b55e-11ea-8370-04124136b4e1.png)

**Example 3**

**_2-line Horizontal Event with Boutens + rubyReserve (with a preceding character/punctuation before span tts:textEmphasis)_** 

`<p begin="140000000t" dur="20000000t" region="bottom-left-justified" ebutts:multiRowAlign="start">〝<span tts:textEmphasis="filled circle before">強</span><span tts:textEmphasis="filled circle before">調</span><span tts:textEmphasis="filled circle before">し</span><span tts:textEmphasis="filled circle before">た</span><span tts:textEmphasis="filled circle before">い</span><span tts:textEmphasis="filled circle before">時</span><span tts:textEmphasis="filled circle before">に</span><span tts:textEmphasis="filled circle before">使</span><br/><span>　</span><span tts:textEmphasis="filled circle after">強</span><span tts:textEmphasis="filled circle after">調</span><span tts:textEmphasis="filled circle after">し</span><span tts:textEmphasis="filled circle after">た</span><span tts:textEmphasis="filled circle after">い</span><span tts:textEmphasis="filled circle after">時</span><span tts:textEmphasis="filled circle after">に</span><span tts:textEmphasis="filled circle after">使</span>〞</p>`

![withBoutnes+character_before_textEmphasis_style](https://user-images.githubusercontent.com/25715295/85467701-64bfca00-b560-11ea-8f85-416784b78190.png)

Test file: 
[RubyReserve_withBoutens_001.xml.zip](https://github.com/sandflow/imscJS/files/4822143/RubyReserve_withBoutens_001.xml.zip)

**Comment by palemieux** [comment] 2020-06-25 15:55
@jbaden It looks like the issue is with the application of boutens on `<br>`. See example below. Can you open a different issue?

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tt xml:lang="ja" xmlns="http://www.w3.org/ns/ttml" ttp:contentProfiles="http://www.w3.org/ns/ttml/profile/imsc1.1/text" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" ttp:timeBase="media" ttp:frameRate="24" ttp:frameRateMultiplier="1000 1001" ttp:tickRate="10000000" xmlns:ebutts="urn:ebu:tt:style" xmlns:itts="http://www.w3.org/ns/ttml/profile/imsc1#styling" xmlns:ittp="http://www.w3.org/ns/ttml/profile/imsc1#parameter" xmlns:ittm="http://www.w3.org/ns/ttml/profile/imsc1#metadata">
	<head>
		<styling>
			<initial tts:color="white" tts:fontFamily="proportionalSansSerif" tts:fontSize="100%" xml:id="initialStyles"/>
			
			<!-- bouten style -->
			<style tts:textEmphasis="filled circle outside" xml:id="bouten-filled-circle-outside"/>
		</styling>
		<layout>
			<!-- General Horiztonal Positioning with ebutts:multiRowAlign -->
			<region ebutts:multiRowAlign="start" tts:displayAlign="after" tts:extent="80.000% 80.000%" tts:origin="10.000% 10.000%" tts:rubyReserve="outside" tts:textAlign="center" xml:id="bottom-left-justified"/>
		
		</layout>
	</head>
	<body>
		<div>
			<p begin="120000000t" dur="10000000t" region="bottom-left-justified" ebutts:multiRowAlign="start"><span style="bouten-filled-circle-outside">強<br/>強</span></p>
      <p begin="130000000t" dur="10000000t" region="bottom-left-justified" ebutts:multiRowAlign="start"><span style="bouten-filled-circle-outside">強</span><br/><span style="bouten-filled-circle-outside">強</span></p>
	    </div>
	</body>
</tt>
```
