### ISSUE TITLE
Runtime error with version 1.1.0

### ISSUE THREAD

**Issue by bbert** [sandflow/imscJS#164] opened 2019-09-02 14:42 UTC
Hello,
It seems there is an issue with last version 1.1.0 of the library.
I integrated this version 1.1.0 in dash.js (current dash.js version is still using version 1.0.2) and I face a bug with the following TTML content:

    <?xml version="1.0" encoding="utf-8"?>
    <tt xmlns="http://www.w3.org/ns/ttml" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en">
	<head>
		<metadata>
			<ttm:title/>
			<ttm:desc/>
			<ttm:copyright/>
		</metadata>
		<styling>
			<style xml:id="style0" />
		</styling>
		<layout>
			<region xml:id="region0" tts:extent="75% 15%" tts:origin="25% 85%" />
		</layout>
	</head>
	<body>
		<div>
			<p begin="435390:00:00.379" end="435390:00:01.338" region="region0" style="style0" xml:id="caption155450">Je sais ce que j&apos;ai Ã  faire.<br/>-Vous devrez</p>
			<p begin="435390:00:01.618" end="435390:00:02.379" region="region0" style="style0" xml:id="caption155451">changer de ville.</p>
		</div>
	</body>
</tt>

At runtime:

![image](https://user-images.githubusercontent.com/5312520/64120681-27a20580-cd9d-11e9-8d9d-edcbbd3dfbf1.png)

With 1.0.2, there is no issue.

Can you check if it comes from the library or the content itself, which seems to be conform (I tested here: http://apps.sandflow.com/imscV/)

**Comment by palemieux** [comment] 2019-09-02 14:58
I am not able to reproduce the issue. Can you provide:

- version of imscJS you are using
- browser version
- OS

P.S.: Something may have gone wrong in the copy-paste of the content since `Ã` is not correct in the french text.

**Comment by tairt** [comment] 2019-09-02 15:13
@bbert Possibly this is just a copy & paste error, but only to be sure this is not the cause: in the copied sample the closing `</tt>` tag is missing.

**Comment by bbert** [comment] 2019-09-02 15:19
imscJS version: 1.1.0
browser version: chrome 76.0.3809.132
OS: Windows10

I made copy-paste directly from network preview of chrome devtools 

Here is the original segment file:
[tf1aas-textstream_11798664_fre=8000-1567403998379.zip](https://github.com/sandflow/imscJS/files/3566565/tf1aas-textstream_11798664_fre.8000-1567403998379.zip)

**Comment by bbert** [comment] 2019-09-02 15:20
Yes for the missing `</tt>` it was a copy & paste error

**Comment by palemieux** [comment] 2019-09-02 15:30
I am running the same configuration and cannot replicate the error.

Perhaps your npm cache be corrupted? Could send over your html.js file?

**Comment by bbert** [comment] 2019-09-02 15:32
[html.zip](https://github.com/sandflow/imscJS/files/3566595/html.zip)

**Comment by palemieux** [comment] 2019-09-02 15:40
@bbert Thanks. The html.js file is identical to my copy. Thinking...

**Comment by bbert** [comment] 2019-09-02 15:40
Have you tried with dash.js?

**Comment by palemieux** [comment] 2019-09-02 15:43
@bbert I do not currently have a dash.js environment setup. What is involved?

**Comment by bbert** [comment] 2019-09-02 15:45
I was just wonder if it may be related with the way the library is integrated within dash.js. Thinking also...

**Comment by bbert** [comment] 2019-09-03 08:11
I have setup the dash.js reference sample with dash.js using version 1.1.0 of imscJS:
http://orange-opensource.github.io/dash.js/samples/dash-if-reference-player/index.html

I manage to reproduce with the sample stream "Subtitles and Captions / TTML Sideloaded XML Subtitles".

You can try yourself and do some debug.

The strange thing is that when you load for the 1st time the stream after having loaded/refeshed the page, then you get the error. But if you stop and (re)load the stream, then you don't get the error...

That's why I was thinking of a problem with imscJS library integration into dash.js.

**Comment by palemieux** [comment] 2019-09-03 18:29
@bbert Thanks for setting up the sandbox!

It looks like ]`element.getBoundingClientRect()`](https://github.com/sandflow/imscJS/blob/8d458897b38a8d6d2d5b6802637437c4ecb5f436/src/main/js/html.js#L984) returns an empty bounding rectangle on the first span that contains text (`e`).

Not sure why this would happen. Need to dig deeper, e.g. is the `div` onto which the subtitle rendered part of the DOM when `renderHTML` is called?

**Comment by palemieux** [comment] 2019-09-03 20:28
@bbert I have created a PR at https://github.com/sandflow/imscJS/pull/165 . Can you give it a try?

**Comment by bbert** [comment] 2019-09-04 07:10
@palemieux I tried and that works fine now. Thanks for the fix.

**Comment by palemieux** [comment] 2019-09-04 19:32
@bbert Any chance to deploy it on the sandbox? If not can you compare the rendering results from 1.0 to 1.1?

**Comment by bbert** [comment] 2019-09-06 09:41
@palemieux 
- version 1.1.0: https://orange-opensource.github.io/dash.js/1.1.0/samples/dash-if-reference-player/index.html
- version PR164: https://orange-opensource.github.io/dash.js/1.1.0_PR164/samples/dash-if-reference-player/index.html

**Closed** 2019-09-16 12:51 UTC
Labels: 1.1, PR open, bug
